### ISSUE TITLE
Postgres DB grows at an exponential rate

### ISSUE THREAD

**Issue by ajith-nataraj** [sentry-kubernetes/charts#1227]
Postgres DB keeps growing at an  exponential rate is there any way we can reduce the disk space increase.

**Comment by ritikrao1** [comment]
nodestore doesn't reduce disk space on cleanup
i reduced my retention from 60 days to 30 days still it showing same disk space used

**Comment by ajith-nataraj** [comment]
yes how can we get it reduced with clean up

**Comment by JustDoItSascha** [comment]
Same problem here

**Comment by ajith-nataraj** [comment]
I connected to sentry DB and ran this below command to check how many dead rows (n_dead_tup) are in that table

SELECT relname, n_dead_tup FROM pg_stat_user_tables;

and found below tables which have high number of dead tuples.

sentry_debugidartifactbundle
sentry_groupedmessage
sentry_monitorcheckin
sentry_eventattachment
nodestore_node

ran 

VACUUM ANALYZE sentry_debugidartifactbundle;
VACUUM ANALYZE sentry_groupedmessage;
VACUUM ANALYZE sentry_monitorcheckin;
VACUUM ANALYZE sentry_eventattachment;
VACUUM ANALYZE nodestore_node;

after the execution of the above commands I see disk usage is bit stable and not increasing at high rate
REF- https://www.datadoghq.com/blog/postgresql-vacuum-monitoring/#dead-rows

**Comment by andrsp** [comment]
I just published custom nodestore for sentry based on elasticsearch
you can try it, feedback welcome :)
https://github.com/andrsp/sentry-nodestore-elastic

**Comment by ajith-nataraj** [comment]
Thank you @andrsp . but this does not solve our problem.
for newer installation its good for the ones which are currently running. we need a solution

**Comment by Mokto** [comment]
@ajith-nataraj's comment seems to be matching https://github.com/getsentry/develop/pull/388/files#diff-5d04353e85d26c1cd3b0b3d862f549957727eeab6d4d66d1cc9428cb076b41bfR100

Maybe we can automate that part.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by ajith-nataraj** [comment]
Actually Disk space is getting stabilsed now. the disk space increased at a higher rate just because of the initial inflow of the data.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by garvit-jain-pw** [comment]
Seams like there is a option to use File-based nodestore backend

https://github.com/getsentry/sentry/pull/41967
